### ISSUE TITLE
make "/ *word */" to "word"

### ISSUE THREAD

**Issue by fredericky123** [zizhongyan/StataImproved#22]
Right now, select any word, press cmd+/, it will become / *word */.
We also need the opposite function of this, can you set "press cmd+\",it will make "/ *word */" to "word".

Or you can set the key to "cmd+shift+/".

Thanks a lot!

**Comment by zizhongyan** [comment]
This is really a good point. I have tried a bit. But to be honest, I still did not find a way to remove the toggle /* word */ within the capacity of the keymap function of sublime.

**Comment by zizhongyan** [comment]
Well. After a cup of coffee, I have added what you described to the package. 

Now we can:
Select any word, press `$` to make it as ${word}. And select ${word}, press `$` to make it as word. 

Select any word, press cmd+ to make the selected word toggled. And press it again to make toggled word  to original word. 

I did not add this function to local macro because I think when wrting loops or Stata programs, it is very often in practice to use local of locals, e.g ``word'' and ```word''' . So one might not wish to remove the quotation marks from `word'.

The package should be updated to package control in about 1-2 hours.
