### ISSUE TITLE
suport for Stata 17?

### ISSUE THREAD

**Issue by fredericky123** [zizhongyan/StataImproved#23]
Do you have plans?

**Comment by gen-li** [comment]
Yes. Please make it compatible with state 17! Much appreciate your hard work!

**Comment by LINCH8** [comment]
need to know this as well

**Comment by zizhongyan** [comment]
Hi All, 
I've just got a Stata 17 license so that I can add the support for stata 17 and test it on my mac. It should work now (after a few hours the package will be updated to package control). 
I would very much appreciate if you could test it on Stata 17 on your machine  as well and let me whether it could work properly or not.
THanks a lot!
