### ISSUE TITLE
Stata 18 Support 

### ISSUE THREAD

**Issue by gen-li** [zizhongyan/StataImproved#33]
Hi Zizhong,

Thank you so much for writing and maintaining this package! I wonder if you could make some updates to this sublime package to make it support Stata 18.

Thanks a lot!

Best,
Gen

**Comment by marshallwg** [comment]
First, @zizhongyan: thank you so much for this wonderful package! It's been a lifesaver after Atom was sunset, but it turned out to be blessing-in-disguise, since I prefer Sublime and your implementation of a Stata editor. 

@gen-li : Depending on your installation (I'm on MacOS), as a short-term kludge, you can modify the StataImproved Python script here: ~/Library/Application Support/Sublime Text/Packages/Stata Improved Editor/StataImproved.py. Beginning on line 100 in my installation, the script recursively searches for the most recent installation; I just copied the chunk related to Stata 17, appended it, and replaced it with 18 (screenshot below). Of course synatx highlighting doesn't work for new commands[1], and I haven't extensively tested it, but I tried a few commands (including new ones like -dtable-) and it seems to be working. I've annotated the modified .py script to so I can revert back to the previous version in case I inadvertently broke something. 

<img width="396" alt="Screenshot 2023-04-26 at 4 14 29 PM" src="https://user-images.githubusercontent.com/60490220/234704300-8c175322-25d2-41dc-a001-b297a43b1793.png">

[1] It looks like this can be modified in the /Stata.tmLanguage file in the same directory, which I haven't gotten around to trying.

**Comment by fredericky123** [comment]
@marshallwg I have installed "stataimproved", why i cannot find the file of "Stata Improved Editor" in " ~/Library/Application Support/Sublime Text/Packages/"

**Comment by marshallwg** [comment]
@fredericky123 In my intallation it's named: 

<img width="679" alt="Screenshot 2023-04-27 at 10 21 03 AM" src="https://user-images.githubusercontent.com/60490220/234909135-a9052bb6-a4b0-41f8-acd0-ff6ba0f092f8.png">

**Comment by fredericky123** [comment]
Surprisingly, I cannot find such file
<img width="265" alt="image" src="https://user-images.githubusercontent.com/13982749/234910460-55d2ab89-6f77-4a67-8c57-d42ce6296eda.png">

**Comment by marshallwg** [comment]
@fredericky123 It's hard to tell what folder you're in from the screenshot you provided. But, you can navigate to the package folder by going to Sublime Text->Settings->Browse Packages from within Sublime. This will open a finder window with the folder where packages are installed. From there, you can navigage to the Stata Improved Editor folder.

<img width="471" alt="Screenshot 2023-04-27 at 11 05 10 AM" src="https://user-images.githubusercontent.com/60490220/234920950-9ffe6abf-8c6b-4daf-ac81-0d7264b80d6a.png">
png">
<img width="797" alt="Screenshot 2023-04-27 at 11 08 34 AM" src="https://user-images.githubusercontent.com/60490220/234921775-27552e8d-8c27-48ec-add2-83c9c972cc66.png">

**Comment by fredericky123** [comment]
Here is my folder, I cannot find a file named "stataimproved.py"
![image](https://user-images.githubusercontent.com/13982749/234926021-eb9f21a0-2f4f-45e2-ad89-57be66976a65.png)
<img width="635" alt="image" src="https://user-images.githubusercontent.com/13982749/234926214-aeb4b161-fc58-4646-99c5-8f64b58560a8.png">

**Comment by marshallwg** [comment]
@fredericky123 I assume you've searched using Spotlight or using other terminal commands (locate, find)? Beyond what I've already shared, I don't have any tips. Sorry.

**Comment by fredericky123** [comment]
Yes, thanks all the same!

**Comment by gen-li** [comment]
@marshallwg @fredericky123 Thank you all for your reply! I cannot find "StataImproved.py" either. I have tried all solutions I have thought of.

**Comment by fredericky123** [comment]
I solved this problem, I manually copied the folder to that path, and modified "StataImproved.py"

**Comment by marshallwg** [comment]
Excellent @gen-li and @fredericky123! Glad this works, and sorry I didn't think of this sooner!

**Comment by zizhongyan** [comment]
Hi there, sorry for the delayed response. I am working on updating the support to Stata 18 and will let you know when it is done.  @gen-li @fredericky123  @marshallwg

**Comment by zizhongyan** [comment]
Hi, I think it works for Stata 18 now. The newest version of the package is **v1.3.16**. Please kindly let me know whether it works on your mac. 

If the package is installed via package control, ST3 will automatically upgrade the package. Of course,  one can force a upgrade by:

- `ctrl+shift+p` to call the package control 
- and type `package control upgrade all packages` and press enter

btw, to check versions, one can `ctrl+shift+p`, and then type `package control list packages`  and press enter

**Comment by marshallwg** [comment]
Seems to be working for me, @zizhongyan! Thank you!
