### ISSUE TITLE
Execute whole file

### ISSUE THREAD

**Issue by acarril** [zizhongyan/StataImproved#4]
First of all, thanks for your awesome work. This is more of a feature request than an issue: it would be great if there was a simple shortcut to execute the whole do file. I know this can be done by (a) selecting all lines first and then executing or by (b) creating Matlab-style blocks, but it would still be a nice improvement if it could be done directly. (a) has the disadvantage that you lose your current selection and (b) just adds unnecessary comments.

Keep up the good work!

**Comment by zizhongyan** [comment]
Thank you for the feedback and suggestion. Yes, I did not really incorporate a single shortcut to execute the whole do-file. The current hot-key ctrl+d without selection is for executing the current line of the code, while in the Stata's in-built do-file editor ctrl+d or cmd+shift+d without selection is for running the whole file. Because based on my daily coding experience, I feel I would more often to execute a current line rather than the whole file.  
 
We definitely can add a shortcut to run the whole file without losing the current selection. I would appreciate if you could possibly suggest a hot-key (or an alternative solution) for this?

**Comment by acarril** [comment]
I definitely agree with you in that the most common action is to execute the current line, but there's definitely times when running the whole file makes sense as well.

Maybe a good idea is to configure Ctrl + Shift + d in such a way that if no code blocks are defined, then it defaults to executing the whole do-file? I think that makes sense and also avoids adding a new combo.

**Comment by zizhongyan** [comment]
Hi acarril, I have added this configuration to the plugin based on your suggestion, i.e. CTRL+SHIFT+d can also be used to execute the WHOLE do-file if no Matlab-style code blocks are defined. Then I've just launched a new release v1.1.2. 

Please let me know if you observe any problem/bug or have any further suggestion!

Many thanks!
